title: GuardianTube
description: GuardianTube empowers parents to restrict access to inappropriate YouTube content and manage screen time with a single, easy-to-use tool. Designed specifically for families, this extension ensures children only view age-appropriate videos while giving parents full control over usage.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
